// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/llm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseText  string                 `protobuf:"bytes,1,opt,name=response_text,json=responseText,proto3" json:"response_text,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetResponseText() string {
	if x != nil {
		return x.ResponseText
	}
	return ""
}

func (x *QueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_llm_proto protoreflect.FileDescriptor

const file_proto_llm_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/llm.proto\x12\x03llm\"W\n" +
	"\fQueryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"N\n" +
	"\rQueryResponse\x12#\n" +
	"\rresponse_text\x18\x01 \x01(\tR\fresponseText\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x83\x01\n" +
	"\n" +
	"LLMService\x129\n" +
	"\x0eProcessRequest\x12\x11.llm.QueryRequest\x1a\x12.llm.QueryResponse\"\x00\x12:\n" +
	"\rStreamRequest\x12\x11.llm.QueryRequest\x1a\x12.llm.QueryResponse\"\x000\x01B0Z.github.com/BYTE-Club-CCNY/Silvercord/api/protob\x06proto3"

var (
	file_proto_llm_proto_rawDescOnce sync.Once
	file_proto_llm_proto_rawDescData []byte
)

func file_proto_llm_proto_rawDescGZIP() []byte {
	file_proto_llm_proto_rawDescOnce.Do(func() {
		file_proto_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_llm_proto_rawDesc), len(file_proto_llm_proto_rawDesc)))
	})
	return file_proto_llm_proto_rawDescData
}

var file_proto_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_llm_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: llm.QueryRequest
	(*QueryResponse)(nil), // 1: llm.QueryResponse
}
var file_proto_llm_proto_depIdxs = []int32{
	0, // 0: llm.LLMService.ProcessRequest:input_type -> llm.QueryRequest
	0, // 1: llm.LLMService.StreamRequest:input_type -> llm.QueryRequest
	1, // 2: llm.LLMService.ProcessRequest:output_type -> llm.QueryResponse
	1, // 3: llm.LLMService.StreamRequest:output_type -> llm.QueryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_llm_proto_init() }
func file_proto_llm_proto_init() {
	if File_proto_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_llm_proto_rawDesc), len(file_proto_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_llm_proto_goTypes,
		DependencyIndexes: file_proto_llm_proto_depIdxs,
		MessageInfos:      file_proto_llm_proto_msgTypes,
	}.Build()
	File_proto_llm_proto = out.File
	file_proto_llm_proto_goTypes = nil
	file_proto_llm_proto_depIdxs = nil
}
