# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\".\n\x0cQueryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"7\n\rQueryResponse\x12\x15\n\rresponse_text\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x83\x01\n\nLLMService\x12\x39\n\x0eProcessRequest\x12\x11.llm.QueryRequest\x1a\x12.llm.QueryResponse\"\x00\x12:\n\rStreamRequest\x12\x11.llm.QueryRequest\x1a\x12.llm.QueryResponse\"\x00\x30\x01\x42\x30Z.github.com/BYTE-Club-CCNY/Silvercord/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/BYTE-Club-CCNY/Silvercord/api/proto'
  _globals['_QUERYREQUEST']._serialized_start=18
  _globals['_QUERYREQUEST']._serialized_end=64
  _globals['_QUERYRESPONSE']._serialized_start=66
  _globals['_QUERYRESPONSE']._serialized_end=121
  _globals['_LLMSERVICE']._serialized_start=124
  _globals['_LLMSERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
