# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\nsilvercord\",\n\nLLMRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"\x8e\x01\n\x0bLLMResponse\x12\x15\n\rresponse_text\x18\x01 \x01(\t\x12\x37\n\x08metadata\x18\x02 \x03(\x0b\x32%.silvercord.LLMResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32Q\n\nLLMService\x12\x43\n\x0eProcessRequest\x12\x16.silvercord.LLMRequest\x1a\x17.silvercord.LLMResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_LLMRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LLMREQUEST']._serialized_start=25
  _globals['_LLMREQUEST']._serialized_end=69
  _globals['_LLMRESPONSE']._serialized_start=72
  _globals['_LLMRESPONSE']._serialized_end=214
  _globals['_LLMRESPONSE_METADATAENTRY']._serialized_start=167
  _globals['_LLMRESPONSE_METADATAENTRY']._serialized_end=214
  _globals['_LLMSERVICE']._serialized_start=216
  _globals['_LLMSERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
